services:
  social-image-generator:
    build: .
    container_name: social-image-generator
    volumes:
      # Mount output directory for generated images
      - ./output:/app/output
      # Mount uploads directory for user images  
      - ./uploads:/app/uploads
      # Mount config directory for custom configurations
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app/src
      - PYTHONDONTWRITEBYTECODE=1
      # Set user ID to match host user (optional)
      - USER_ID=1000
      - GROUP_ID=1000
    ports:
      - "5000:5000" # Flask API server port
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "python", "-c", "from enhanced_social_generator import EnhancedSocialImageGenerator; print('OK')" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - social-image-network
    # Ensure container runs as correct user
    user: "1000:1000"

  # Development service with hot reload
  dev:
    build: .
    container_name: social-image-generator-dev
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app/src
      - PYTHONDONTWRITEBYTECODE=1
    command: tail -f /dev/null # Keep container running for development
    ports:
      - "8000:8000" # For future API endpoints
    profiles:
      - dev
    networks:
      - social-image-network
    user: "1000:1000"

  # Test service
  test:
    build: .
    container_name: social-image-generator-test
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app/src
      - PYTHONDONTWRITEBYTECODE=1
    command: python -m pytest tests/ -v
    profiles:
      - test
    networks:
      - social-image-network
    user: "1000:1000"

networks:
  social-image-network:
    driver: bridge

volumes:
  uploads:
    driver: local
  output:
    driver: local