services:
  social-image-generator:
    build: .
    container_name: social-image-generator
    volumes:
      # All data is stored within the container
      # Optional: Mount volumes only if you want to persist data externally
      - uploads_data:/app/uploads
      - generated_data:/app/generated
      - output_data:/app/output
      - cache_data:/app/cache
      - fonts_data:/app/assets/fonts/downloaded
    environment:
      - PYTHONPATH=/app/src
      - PYTHONDONTWRITEBYTECODE=1
      # Disable Flask debug mode in production
      - FLASK_ENV=production
      # Enable font downloads within container
      - ALLOW_FONT_DOWNLOADS=true
    ports:
      - "${PORT:-5000}:5000" # Configurable port with fallback to 5000
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "python", "-c", "import flask; from src.enhanced_social_generator import EnhancedSocialImageGenerator; print('OK')" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - social-image-network

  # Development service with hot reload
  dev:
    build: .
    container_name: social-image-generator-dev
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app/src
      - PYTHONDONTWRITEBYTECODE=1
    command: tail -f /dev/null # Keep container running for development
    ports:
      - "${DEV_PORT:-8000}:8000" # Configurable dev port
    profiles:
      - dev
    networks:
      - social-image-network
    # Remove user specification for better Linux compatibility

  # Test service
  test:
    build: .
    container_name: social-image-generator-test
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONPATH=/app/src
      - PYTHONDONTWRITEBYTECODE=1
    command: python -m pytest tests/ -v
    profiles:
      - test
    networks:
      - social-image-network
    # Remove user specification for better Linux compatibility

networks:
  social-image-network:
    driver: bridge

volumes:
  uploads_data:
    driver: local
  generated_data:
    driver: local
  output_data:
    driver: local
  cache_data:
    driver: local
  fonts_data:
    driver: local