version: '3.8'

services:
  social-image-generator:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./generated:/app/generated
      - ./output:/app/output
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app/src
      - FLASK_APP=social_image_api.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - social-image-network

networks:
  social-image-network:
    driver: bridge
